// <auto-generated />
//
// This file was automatically generated by PocosGenerator.csx, inspired from the PetaPoco T4 Template
// Do not make changes directly to this file - edit the PocosGenerator.GenerateClass() method in the PocosGenerator.Core.csx file instead
// 

using System;
using Dapper.Contrib.Extensions;
using System.Collections.Generic;

namespace com.apthai.CRMMobile.Model.CRMMobile
{
  

    [Table("CS_UserProfile")]
    public partial class CSUserProfile
    {
        public int? ID { get; set; }
        public int? CRMUserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CreateDate { get; set; }
        public int? PINCode { get; set; }
    }

    [Table("UserLogin")]
    public partial class UserLogin
    {
        [Key]
        public int UserLoginID { get; set; }
        public string UserPhoneNumber { get; set; }
        public string LoginDate { get; set; }
        public string DeviceID { get; set; }
        public string DeviceType { get; set; }
        public string UserToken { get; set; }
        public string FireBaseToken { get; set; }
    }

    [Table("UserProfile")]
    public partial class UserProfile
    {
        [Key]
        public int UserProfileID { get; set; }
        public string CRMContactID { get; set; }
        public string TitleExtTH { get; set; }
        public string FirstNameTH { get; set; }
        public string MiddleNameTH { get; set; }
        public string LastNameTH { get; set; }
        public string Nickname { get; set; }
        public string TitleExtEN { get; set; }
        public string FirstNameEN { get; set; }
        public string MiddleNameEN { get; set; }
        public string LastNameEN { get; set; }
        public string CitizenIdentityNo { get; set; }
        public string Created { get; set; }
        public string CreatedBy { get; set; }
        public string Updated { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public int? PINCode { get; set; }
    }
}
