// <auto-generated />
//
// This file was automatically generated by PocosGenerator.csx, inspired from the PetaPoco T4 Template
// Do not make changes directly to this file - edit the PocosGenerator.GenerateClass() method in the PocosGenerator.Core.csx file instead
// 

using System;
using Dapper.Contrib.Extensions;
using System.Collections.Generic;

namespace com.apthai.CRMMobile.Model.DefectAPI
{
  

    [Table("AccessKeyControl")]
    public partial class AccessKeyControl
    {
        [Key]
        public int ID { get; set; }
        public string EmpCode { get; set; }
        public string AccessKey { get; set; }
        public DateTime? LoginDate { get; set; }
    }

    [Table("AggregatedCounter")]
    public partial class AggregatedCounter
    {
        [ExplicitKey]
        public string Key { get; set; }
        public long Value { get; set; }
        public DateTime? ExpireAt { get; set; }
    }

    [Table("callarea")]
    public partial class callarea
    {
        [Key]
        public int callarea_id { get; set; }
        public int? calltype_id { get; set; }
        public string callarea_name { get; set; }
        public int? chk_type { get; set; }
        public int? active { get; set; }
        public string responsible { get; set; }
        public string producttypecate { get; set; }
        public int? sequence { get; set; }
    }

    [Table("callCachingTokens")]
    public partial class callCachingToken
    {
        public string TableChangedGroupId { get; set; }
        public Guid TableChangedTokenData { get; set; }
        public DateTime TableChangedDatime { get; set; }
    }

    [Table("calldescriptions")]
    public partial class calldescription
    {
        [Key]
        public int calldesc_id { get; set; }
        public int? callarea_id { get; set; }
        public string description { get; set; }
        public string idpiority { get; set; }
        public string priority_time { get; set; }
        public int? majordefect_id { get; set; }
        public int? chk24 { get; set; }
        public string QC6 { get; set; }
        public int? active { get; set; }
        public string remark { get; set; }
        public int? priority_day { get; set; }
        public int? ISpiority { get; set; }
        public int? ISlead { get; set; }
    }

    [Table("callMAuditCaseType")]
    public partial class callMAuditCaseType
    {
        [ExplicitKey]
        public int AuditCaseType_id { get; set; }
        public string ComplainAuditType { get; set; }
        public string AuditResultType { get; set; }
        public string CaseTypeDetail { get; set; }
        public int? Active { get; set; }
    }

    [Table("callMAuditMemoGroup")]
    public partial class callMAuditMemoGroup
    {
        [Key]
        public int AuditMemoGroup_id { get; set; }
        public string AuditMemoGroupDetail { get; set; }
        public string ComplainAuditType { get; set; }
        public int? SeqOrder { get; set; }
    }

    [Table("callMAuditResultType")]
    public partial class callMAuditResultType
    {
        [ExplicitKey]
        public int AuditResultType_Id { get; set; }
        public string ComplainAuditType { get; set; }
        public string AuditResultTypeDesc { get; set; }
    }

    [Table("callResource")]
    public partial class callResource
    {
        [Key]
        public int ResourceId { get; set; }
        public int? ResourceType { get; set; }
        public string ResourceTagCode { get; set; }
        public string ResourceTagSubCode { get; set; }
        public Guid? ResourceGroupSet { get; set; }
        public int? ResourceGroupOrder { get; set; }
        public string ResourceMineType { get; set; }
        public string ProjectNo { get; set; }
        public string SerialNo { get; set; }
        public int? JobNo { get; set; }
        public int? ComplainId { get; set; }
        public int? DtlComplainId { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }
        public string UserId { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? StorageServerId { get; set; }
        public string DeviceId { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime? UpdateDate { get; set; }
        public int? TDefectId { get; set; }
        public int? TDefectDetailId { get; set; }
        public string Client_Id { get; set; }
        public DateTime? Client_SyncDate { get; set; }
        public string Tag { get; set; }
        public string RowState { get; set; }
        public int? TDefectCheckListId { get; set; }
        public long? FileLength { get; set; }
        public string ResourceTagSubCodeVersion { get; set; }
    }

    [Table("callResource_bk")]
    public partial class callResourcebk
    {
        public int ResourceId { get; set; }
        public int? ResourceType { get; set; }
        public string ResourceTagCode { get; set; }
        public string ResourceTagSubCode { get; set; }
        public Guid? ResourceGroupSet { get; set; }
        public int? ResourceGroupOrder { get; set; }
        public string ResourceMineType { get; set; }
        public string ProjectNo { get; set; }
        public string SerialNo { get; set; }
        public int? JobNo { get; set; }
        public int? ComplainId { get; set; }
        public int? DtlComplainId { get; set; }
        public string FilePath { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }
        public string UserId { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? StorageServerId { get; set; }
        public string DeviceId { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime? UpdateDate { get; set; }
        public int? TDefectId { get; set; }
        public int? TDefectDetailId { get; set; }
        public string Client_Id { get; set; }
        public DateTime? Client_SyncDate { get; set; }
        public string Tag { get; set; }
        public string RowState { get; set; }
        public int? TDefectCheckListId { get; set; }
    }

    [Table("callStaComplain")]
    public partial class callStaComplain
    {
        public string IdStaComplain { get; set; }
        public string StaComplain { get; set; }
        public int? active { get; set; }
    }

    [Table("callStaUnit")]
    public partial class callStaUnit
    {
        [Key]
        public int unitstatus_id { get; set; }
        public string IdStaUnit { get; set; }
        public string StaUnit { get; set; }
        public string active { get; set; }
    }

    [Table("callStorageServer")]
    public partial class callStorageServer
    {
        [ExplicitKey]
        public int StorageServerId { get; set; }
        public string StorageServerRootUrl { get; set; }
        public string StoragePhysicalPath { get; set; }
        public string StorageNetworkFileServiceType { get; set; }
        public string StorageNetworkFileServicePath { get; set; }
    }

    [Table("callsubsta")]
    public partial class callsubsta
    {
        [ExplicitKey]
        public int subid { get; set; }
        public string substaname { get; set; }
        public int? active { get; set; }
    }

    [Table("callTDefect")]
    public partial class callTDefect
    {
        [Key]
        public int TDefectId { get; set; }
        public string RowState { get; set; }
        public bool RowActive { get; set; }
        public string Client_Id { get; set; }
        public DateTime? Client_SyncDate { get; set; }
        public string TDefectDocNo { get; set; }
        public string TDefectStatus { get; set; }
        public string TDefectSubStatus { get; set; }
        public string ProductId { get; set; }
        public string ItemId { get; set; }
        public string DeviceId { get; set; }
        public string CreateUserId { get; set; }
        public string UpdateUserId { get; set; }
        public int? CustRoundAuditNo_Rn { get; set; }
        public DateTime? CustRoundAuditDate_Last { get; set; }
        public string CustRoundAudit_JsonLog { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string Desciption { get; set; }
        public DateTime? DocOpenDate { get; set; }
        public DateTime? DocDueCloseDate { get; set; }
        public string MechanicId { get; set; }
        public string MechanicName { get; set; }
        public string SellerId { get; set; }
        public string SallerName { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public DateTime? DocDueTransferDate { get; set; }
        public string ContactID { get; set; }
        public string ContactName { get; set; }
        public bool? DocIsActive { get; set; }
        public bool? DocIsExternalAudit { get; set; }
        public bool? DocIsReqUnitReceiveAttachFile { get; set; }
    }

    [Table("callTDefect_bk_11Nov2015")]
    public partial class callTDefectbk11Nov2015
    {
        public int TDefectId { get; set; }
        public string RowState { get; set; }
        public bool RowActive { get; set; }
        public string Client_Id { get; set; }
        public DateTime? Client_SyncDate { get; set; }
        public string TDefectDocNo { get; set; }
        public string TDefectStatus { get; set; }
        public string TDefectSubStatus { get; set; }
        public string ProductId { get; set; }
        public string ItemId { get; set; }
        public string DeviceId { get; set; }
        public string CreateUserId { get; set; }
        public string UpdateUserId { get; set; }
        public int? CustRoundAuditNo_Rn { get; set; }
        public DateTime? CustRoundAuditDate_Last { get; set; }
        public string CustRoundAudit_JsonLog { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string Desciption { get; set; }
        public DateTime? DocOpenDate { get; set; }
        public DateTime? DocDueCloseDate { get; set; }
        public string MechanicId { get; set; }
        public string MechanicName { get; set; }
        public string SellerId { get; set; }
        public string SallerName { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public DateTime? DocDueTransferDate { get; set; }
        public string ContactID { get; set; }
        public string ContactName { get; set; }
        public bool? DocIsActive { get; set; }
        public bool? DocIsExternalAudit { get; set; }
        public bool? DocIsReqUnitReceiveAttachFile { get; set; }
    }

    [Table("callTDefectAppMessageLog")]
    public partial class callTDefectAppMessageLog
    {
        [Key]
        public int AppMessageId { get; set; }
        public int TDefectId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public DateTime? RecordDate { get; set; }
        public int? Status { get; set; }
    }

    [Table("callTDefectAppointment")]
    public partial class callTDefectAppointment
    {
        [Key]
        public int DFAPID { get; set; }
        public string ProductId { get; set; }
        public string unitnumber { get; set; }
        public int? idjobno { get; set; }
        public DateTime? appdate { get; set; }
        public DateTime? appdate_putoff { get; set; }
        public int? confirmapp { get; set; }
        public DateTime? appdate2 { get; set; }
        public DateTime? appdate2_putoff { get; set; }
        public int? confirmapp2 { get; set; }
        public DateTime? appdate3 { get; set; }
        public DateTime? appdate3_putoff { get; set; }
        public int? confirmapp3 { get; set; }
        public DateTime? appdate4 { get; set; }
        public DateTime? appdate4_putoff { get; set; }
        public int? confirmapp4 { get; set; }
        public DateTime? appdate5 { get; set; }
        public DateTime? appdate5_putoff { get; set; }
        public int? confirmapp5 { get; set; }
        public string appnote { get; set; }
        public string appby { get; set; }
        public string confirmappby { get; set; }
        public string cusomer_id { get; set; }
        public string cusomer_name { get; set; }
        public string customer_contacttel { get; set; }
    }

    [Table("callTDefectCheckList")]
    public partial class callTDefectCheckList
    {
        [Key]
        public int TDefectCheckListId { get; set; }
        public string RowState { get; set; }
        public bool RowActive { get; set; }
        public string Client_Id { get; set; }
        public DateTime? Client_SyncDate { get; set; }
        public string ProductId { get; set; }
        public string ItemId { get; set; }
        public string CheckListStatus { get; set; }
        public string CheckListData { get; set; }
        public int? CheckListDataRowCount { get; set; }
        public string DeviceId { get; set; }
        public string Tag { get; set; }
        public bool? IsServerLockRow { get; set; }
        public int? TDefectId { get; set; }
        public string TDefect_Client_Id { get; set; }
        public string CreateUserId { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
    }

    [Table("callTDefectCustRoundAuditLog")]
    public partial class callTDefectCustRoundAuditLog
    {
        [ExplicitKey]
        public int TDefectId { get; set; }
        public int RoundAuditNo { get; set; }
        public DateTime RoundAuditDate { get; set; }
    }

    [Table("callTDefectDetail")]
    public partial class callTDefectDetail
    {
        [Key]
        public int TDefectDetailId { get; set; }
        public string RowState { get; set; }
        public bool RowActive { get; set; }
        public string Client_Id { get; set; }
        public DateTime? Client_SyncDate { get; set; }
        public int TDefectId { get; set; }
        public string TDefectDocNo { get; set; }
        public string ProductId { get; set; }
        public string ItemId { get; set; }
        public string TDefectDetailStatus { get; set; }
        public string TDefectDetailSubStatus { get; set; }
        public string TDefectDetailDesc { get; set; }
        public int? CallTypeId { get; set; }
        public int? CallAreaId { get; set; }
        public int? CallDescId { get; set; }
        public int? CallPointId { get; set; }
        public int? CallSubPointId { get; set; }
        public string DeviceId { get; set; }
        public string Tag { get; set; }
        public string CreateUserId { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string FloorPlan_ImageId { get; set; }
        public double? FloorPlan_X { get; set; }
        public double? FloorPlan_Y { get; set; }
        public int? TaskNo { get; set; }
        public string TaskMarkName { get; set; }
        public string FloorPlanSet { get; set; }
        public int? CustRoundAuditNo { get; set; }
        public DateTime? CustRoundAuditDate { get; set; }
        public DateTime? CustRoundAuditDueCloseDate { get; set; }
        public bool? IsServerLockRow { get; set; }
        public DateTime? TaskOpenDate { get; set; }
        public DateTime? TaskProcessDate { get; set; }
        public DateTime? TaskActualFinishDate { get; set; }
        public DateTime? TaskActualCloseDate { get; set; }
    }

    [Table("callTDefectDetail_bk_11Nov2015")]
    public partial class callTDefectDetailbk11Nov2015
    {
        public int TDefectDetailId { get; set; }
        public string RowState { get; set; }
        public bool RowActive { get; set; }
        public string Client_Id { get; set; }
        public DateTime? Client_SyncDate { get; set; }
        public int TDefectId { get; set; }
        public string TDefectDocNo { get; set; }
        public string ProductId { get; set; }
        public string ItemId { get; set; }
        public string TDefectDetailStatus { get; set; }
        public string TDefectDetailSubStatus { get; set; }
        public string TDefectDetailDesc { get; set; }
        public int? CallTypeId { get; set; }
        public int? CallAreaId { get; set; }
        public int? CallDescId { get; set; }
        public int? CallPointId { get; set; }
        public int? CallSubPointId { get; set; }
        public string DeviceId { get; set; }
        public string Tag { get; set; }
        public string CreateUserId { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string FloorPlan_ImageId { get; set; }
        public double? FloorPlan_X { get; set; }
        public double? FloorPlan_Y { get; set; }
        public int? TaskNo { get; set; }
        public string TaskMarkName { get; set; }
        public string FloorPlanSet { get; set; }
        public int? CustRoundAuditNo { get; set; }
        public DateTime? CustRoundAuditDate { get; set; }
        public DateTime? CustRoundAuditDueCloseDate { get; set; }
        public bool? IsServerLockRow { get; set; }
        public DateTime? TaskOpenDate { get; set; }
        public DateTime? TaskProcessDate { get; set; }
        public DateTime? TaskActualFinishDate { get; set; }
        public DateTime? TaskActualCloseDate { get; set; }
    }

    [Table("callTFloorPlanImage")]
    public partial class callTFloorPlanImage
    {
        [ExplicitKey]
        public string FloorPlanImageId { get; set; }
        public string ProductTypeCate { get; set; }
        public string ProductId { get; set; }
        public string Floor { get; set; }
        public string UnitLayoutType { get; set; }
        public string FilePath { get; set; }
        public int? StorageServerId { get; set; }
        public bool? IsActive { get; set; }
    }

    [Table("callTypCallDialStatus")]
    public partial class callTypCallDialStatus
    {
        [ExplicitKey]
        public int callDialTypeId { get; set; }
        public string callDialTypeDesc { get; set; }
        public int? IsActive { get; set; }
        public int? FormType { get; set; }
    }

    [Table("callTypComplain")]
    public partial class callTypComplain
    {
        public int IdTypComplain { get; set; }
        public string TypComplain { get; set; }
        public string TypGroup { get; set; }
        public string DueDay { get; set; }
        public string TypGroupname { get; set; }
    }

    [Table("callTypComplain_O")]
    public partial class callTypComplainO
    {
        public string IdTypComplain { get; set; }
        public string TypComplain { get; set; }
        public string TypGroup { get; set; }
        public string DueDay { get; set; }
        public string TypGroupname { get; set; }
    }

    [Table("callTypCustomer")]
    public partial class callTypCustomer
    {
        [Key]
        public int custtype_id { get; set; }
        public string IdTypCustomer { get; set; }
        public string TypCustomer { get; set; }
    }

    [Table("calltype")]
    public partial class calltype
    {
        [ExplicitKey]
        public int calltype_id { get; set; }
        public string _calltype { get; set; }
        public int? active { get; set; }
    }

    [Table("callTypGroup")]
    public partial class callTypGroup
    {
        public string IdTypGroup { get; set; }
        public string TypGroup { get; set; }
        public string DesGroup { get; set; }
    }

    [Table("callTypPiority")]
    public partial class callTypPiority
    {
        public string IdTypPiority { get; set; }
        public string TypPiority { get; set; }
    }

    [Table("callTypRepare")]
    public partial class callTypRepare
    {
        public string IdTypRepare { get; set; }
        public string TypRepare { get; set; }
        public string CodeRepare { get; set; }
    }

    [Table("callTypResource")]
    public partial class callTypResource
    {
        [ExplicitKey]
        public int ResourceTypeId { get; set; }
        public int? ResourceScopeId { get; set; }
        public string ResourceMineType { get; set; }
        public string ResourceTypeDesc { get; set; }
    }

    [Table("callTypResourceScope")]
    public partial class callTypResourceScope
    {
        [ExplicitKey]
        public int ResourceScopeId { get; set; }
        public string ResourceScopeDesc { get; set; }
    }

    [Table("callTypSource")]
    public partial class callTypSource
    {
        public string IdTypSource { get; set; }
        public string TypSource { get; set; }
        public int? active { get; set; }
    }

    [Table("Counter")]
    public partial class Counter
    {
        public string Key { get; set; }
        public int Value { get; set; }
        public DateTime? ExpireAt { get; set; }
    }

    [Table("cusnote")]
    public partial class cusnote
    {
        public string Cusid { get; set; }
        public string ftelno { get; set; }
        public string expct_date { get; set; }
        public string FREPROJ { get; set; }
        public string FSERIALNO { get; set; }
    }

    [Table("custnote")]
    public partial class custnote
    {
        [Key]
        public int custnote_id { get; set; }
        public string note { get; set; }
        public DateTime? update_date { get; set; }
        public string flag_del { get; set; }
        public string update_by { get; set; }
        public string fcucode { get; set; }
        public string FREPROJ { get; set; }
        public string FSERIALNO { get; set; }
    }

    [Table("defectchecklist")]
    public partial class defectchecklist
    {
        [Key]
        public int clid { get; set; }
        public string checklistname { get; set; }
        public string checklisttype { get; set; }
        public int? active { get; set; }
    }

    [Table("defectsubchecklist")]
    public partial class defectsubchecklist
    {
        [Key]
        public int id { get; set; }
        public int? clid { get; set; }
        public string name { get; set; }
        public int? active { get; set; }
    }

    [Table("department")]
    public partial class department
    {
        [Key]
        public int dept_id { get; set; }
        public string _department { get; set; }
        public string short_name { get; set; }
        public string flag_del { get; set; }
        public DateTime? update_date { get; set; }
        public string update_by { get; set; }
        public int? active { get; set; }
    }

    [Table("dtluser")]
    public partial class dtluser
    {
        [ExplicitKey]
        public string User_Id { get; set; }
        public string EmployeeId { get; set; }
        public string Password { get; set; }
        public string Company { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public string Name { get; set; }
        public string JobTitle { get; set; }
        public string Location { get; set; }
        public string Tel { get; set; }
        public string Tel2 { get; set; }
        public string MTel { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public string flagProject { get; set; }
        public string flagClose { get; set; }
        public string typeuser { get; set; }
        public string processID { get; set; }
        public string PSEProcessid { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public DateTime? datestart { get; set; }
        public string jobtime { get; set; }
        public string joblevel { get; set; }
        public string provelavel { get; set; }
        public string jobtype { get; set; }
        public string address { get; set; }
        public DateTime? birthday { get; set; }
        public string Jobtimeset { get; set; }
        public double? boardactive { get; set; }
        public DateTime? ResignDate { get; set; }
        public int? ISfixit { get; set; }
        public double? active { get; set; }
    }

    [Table("dtlusergroup")]
    public partial class dtlusergroup
    {
        [ExplicitKey]
        public string UserGroup_Id { get; set; }
        public string User_Id { get; set; }
    }

    [Table("dtproperties")]
    public partial class dtproperty
    {
        [Key]
        public int id { get; set; }
        public int? objectid { get; set; }
        public string property { get; set; }
        public string value { get; set; }
        public string uvalue { get; set; }
        public byte[] lvalue { get; set; }
        public int version { get; set; }
    }

    [Table("FXMLocDistrict")]
    public partial class FXMLocDistrict
    {
        public string DistrictCKey { get; set; }
        public string DistrictID { get; set; }
        public string DistrictName { get; set; }
    }

    [Table("FXMLocProvince")]
    public partial class FXMLocProvince
    {
        public string ProvinceCKey { get; set; }
        public string ProvinceID { get; set; }
        public string ProvinceName { get; set; }
    }

    [Table("FXMLocSubDistrict")]
    public partial class FXMLocSubDistrict
    {
        public string SubDistrictCKey { get; set; }
        public string SubDistrictID { get; set; }
        public string SubDistrictName { get; set; }
    }

    [Table("Hash")]
    public partial class Hash
    {
        [ExplicitKey]
        public string Key { get; set; }
        public string Field { get; set; }
        public string Value { get; set; }
        public string ExpireAt { get; set; }
    }

    [Table("ICON_EntForms_Brand")]
    public partial class ICONEntFormsBrand
    {
        public string SBUID { get; set; }
        [ExplicitKey]
        public string BrandID { get; set; }
        public string BrandName { get; set; }
        public bool? DeleteFlag { get; set; }
    }

    [Table("ICON_EntForms_Model")]
    public partial class ICONEntFormsModel
    {
        public int ItemID { get; set; }
        [ExplicitKey]
        public string ModelID { get; set; }
        public long? OwnerId { get; set; }
        public string BUID { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string ModelArae { get; set; }
        public string ModelHomeSize { get; set; }
        public string ModelArea2 { get; set; }
        public string ModelFloorLiving { get; set; }
        public string ModelFloor2 { get; set; }
        public string ModelFloor1 { get; set; }
        public string ModelFloorBathroom { get; set; }
        public string ModelFloorRoom { get; set; }
        public string ModelFloorKitchen { get; set; }
        public string ModelceilingFloor { get; set; }
        public string ModelCeilingBathroom { get; set; }
        public string ModelSanitary { get; set; }
        public string ModelWall { get; set; }
        public string ModelWindowScreen { get; set; }
        public string ModelGlass { get; set; }
        public string ModelDoorWindow { get; set; }
        public string ModelAccessory { get; set; }
        public string ModelEP { get; set; }
        public string ModelB { get; set; }
        public string ModelSw { get; set; }
        public string ModelFloorCarPark { get; set; }
        public string ModelFloorETC { get; set; }
        public string ModelCeilingCarPark { get; set; }
        public string ModelCeilingO { get; set; }
        public string ModelRoof { get; set; }
        public string ModelPump { get; set; }
        public string ModelHeat { get; set; }
        public string ModelHeat2 { get; set; }
        public string ModelArt { get; set; }
        public string ModelPromotion { get; set; }
        public string ModelCeilingBathroomq { get; set; }
        public string ModelHomeThai { get; set; }
        public string ModelHomeEng { get; set; }
        public string ModelUnit { get; set; }
        public string UnitType { get; set; }
        public string Model { get; set; }
        public string ModelType { get; set; }
        public bool? BOI { get; set; }
        public string UnitCountEnglish { get; set; }
        public decimal? StandardPrice { get; set; }
        public decimal? StandardCost { get; set; }
        public decimal? PriceSQM { get; set; }
        public decimal? BuiltInPriceSQM { get; set; }
        public decimal? StandardAreaSQW { get; set; }
        public decimal? StandardAreaSQM { get; set; }
        public decimal? NumberBedRoom { get; set; }
        public decimal? NumberBathRoom { get; set; }
        public decimal? StandardBuiltInSQM { get; set; }
        public string Electric { get; set; }
        public string Water { get; set; }
        public string TypeOfRealEstate { get; set; }
        public string ShortName { get; set; }
        public string UnitCountThai { get; set; }
        public decimal? PriceMeterElectric { get; set; }
        public decimal? PriceMeterWater { get; set; }
        public string FrontWidth { get; set; }
        public decimal? PreferUnit { get; set; }
        public decimal? PreferUnitMinimum { get; set; }
    }

    [Table("ICON_EntForms_Products")]
    public partial class ICONEntFormsProduct
    {
        public string ItemID { get; set; }
        [ExplicitKey]
        public string ProductID { get; set; }
        public string Project { get; set; }
        public string Producttype { get; set; }
        public long? OwnerId { get; set; }
        public string BUID { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string Area { get; set; }
        public string BuildingProduct { get; set; }
        public decimal? UnitTotal { get; set; }
        public DateTime? StartSale { get; set; }
        public string TimeOpenSale { get; set; }
        public int? ParkingUnits { get; set; }
        public string Cost { get; set; }
        public decimal? CostProduct { get; set; }
        public string RoadProduct { get; set; }
        public string SystemWater { get; set; }
        public string PipeWater { get; set; }
        public string ElecotricProject { get; set; }
        public string Water { get; set; }
        public string TravelPresent { get; set; }
        public string TravelFuture { get; set; }
        public string EducationArea { get; set; }
        public string Hospital { get; set; }
        public string Entertainment { get; set; }
        public string Productfacility { get; set; }
        public string SBUID { get; set; }
        public string BrandID { get; set; }
        public string Notation1 { get; set; }
        public string Notation2 { get; set; }
        public string UtilityAttornyID { get; set; }
        public string UtilityAttornyAge { get; set; }
        public string UtilityAttornyName { get; set; }
        public string AttornyName1 { get; set; }
        public string AttornyName2 { get; set; }
        public string UtilityAttornyAddress { get; set; }
        public string UtilityAttornySoi { get; set; }
        public string UtilityAttornyRoad { get; set; }
        public string UtilityAttornySubDistrict { get; set; }
        public string UtilityAttornyDistrict { get; set; }
        public string UtilityAttornyProvience { get; set; }
        public bool? BOI { get; set; }
        public string BOINumber { get; set; }
        public string ElectricAreaOffice { get; set; }
        public string ElectriceChiefReceptionName { get; set; }
        public string ElectriceChiefPosition { get; set; }
        public string ElectriceBookNumberAppoint { get; set; }
        public string ElectriceWitnessName1 { get; set; }
        public string ElectriceWitnessName2 { get; set; }
        public string LandNumber { get; set; }
        public string OtherInformation { get; set; }
        public string ProductStatus { get; set; }
        public string WaterAreaOffice { get; set; }
        public string WaterAreaOfficeNumber { get; set; }
        public string WaterSubDistrict { get; set; }
        public string WaterOfficeRoad { get; set; }
        public string WaterProvience { get; set; }
        public string WaterDistrict { get; set; }
        public string LicenceLandNumber { get; set; }
        public DateTime? LicenceLandIssueDate { get; set; }
        public DateTime? LicenceLandExpireDate { get; set; }
        public string LicenceProductNumber { get; set; }
        public DateTime? LicenceProductIssueDate { get; set; }
        public DateTime? LicenceProductExpireDate { get; set; }
        public string LicenceModelNumber { get; set; }
        public DateTime? LicenceModelIssueDate { get; set; }
        public DateTime? LicenceModelExpireDate { get; set; }
        public string LicencePlanNumber { get; set; }
        public DateTime? LicencePlanIssueDate { get; set; }
        public DateTime? LicencePlanExpireDate { get; set; }
        public string LicenceLandSaleNumber { get; set; }
        public DateTime? LicenceLandSaleIssueDate { get; set; }
        public DateTime? LicenceLandSaleExpireDate { get; set; }
        public string LicencelGarbageNumber { get; set; }
        public DateTime? LicencelGarbageIssueDate { get; set; }
        public DateTime? LicencelGarbageExpireDate { get; set; }
        public string LicenceRoadNumber { get; set; }
        public DateTime? LicenceRoadIssueDate { get; set; }
        public DateTime? LicenceRoadExpireDate { get; set; }
        public string LicenceWaterFlowNumber { get; set; }
        public DateTime? LicenceWaterFlowIssueDate { get; set; }
        public DateTime? LicenceWaterFlowExpireDate { get; set; }
        public string LicenceElectricNumber { get; set; }
        public DateTime? LicenceElectricIssueDate { get; set; }
        public DateTime? LicenceElectricExpireDate { get; set; }
        public string LicenceWaterNumber { get; set; }
        public DateTime? LicenceWaterIssueDate { get; set; }
        public DateTime? LicenceWaterExpireDate { get; set; }
        public string LicenceSWLNumber { get; set; }
        public DateTime? LicenceSWLIssueDate { get; set; }
        public DateTime? LicenceSWLExpireDate { get; set; }
        public string LicenceBroadNumber { get; set; }
        public DateTime? LicenceBroadIssueDate { get; set; }
        public DateTime? LicenceBroadExpireDate { get; set; }
        public string LicenceFillNumber { get; set; }
        public DateTime? LicenceFillIssueDate { get; set; }
        public DateTime? LicenceFillExpireDate { get; set; }
        public DateTime? CloseSale { get; set; }
        public string CompanyID { get; set; }
        public string PfreprjNoSap { get; set; }
        public string PcscnSap { get; set; }
        public string YfreprjNoKS { get; set; }
        public string YPcscnSapKS { get; set; }
        public decimal? PublicFundRate { get; set; }
        public decimal? SinkingFundRate { get; set; }
        public decimal? InsurancePremiumBuilding { get; set; }
        public double? PublicFundMonths { get; set; }
        public DateTime? PublicfundEndDate { get; set; }
        public DateTime? AttoryIssueDate { get; set; }
        public string ContractIssueDate { get; set; }
        public decimal? ContractTransferfee { get; set; }
        public decimal? UnitTransferfee { get; set; }
        public string ProductOwner_CS { get; set; }
        public string witness1 { get; set; }
        public string witness2 { get; set; }
        public decimal? FineHousingAll { get; set; }
        public decimal? FineHousingDay { get; set; }
        public double? FineRate { get; set; }
        public decimal? LoanAmount { get; set; }
        public string Loanbank { get; set; }
        public string LoanbankEng { get; set; }
        public decimal? PreferUnit { get; set; }
        public string Rai { get; set; }
        public string Ngarn { get; set; }
        public string SquareWah { get; set; }
        public string ProjectNameEng { get; set; }
        public string Address { get; set; }
        public string Building { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string PostCode { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string BankProjectAP { get; set; }
        public string AttornyNameTransfer { get; set; }
        public string BankProjectAPEng { get; set; }
        public string AttornyName1Eng { get; set; }
        public string AttornyName2Eng { get; set; }
        public string witness1Eng { get; set; }
        public string witness2Eng { get; set; }
        public int? RTPExcusive { get; set; }
        public decimal? SumProductPrice { get; set; }
        public decimal? PreferUnitMinimum { get; set; }
        public string PreLicenceLandNumber { get; set; }
        public DateTime? PreLicenceLandIssueDate { get; set; }
        public DateTime? PreLicenceLandExpireDate { get; set; }
        public string PreferApprove { get; set; }
        public string PositionPerferApprove { get; set; }
        public string OldCompanyID { get; set; }
        public string SAPProductID { get; set; }
        public string SAPProfitCenter { get; set; }
        public string SAPCostCenter { get; set; }
        public bool isValueCondo { get; set; }
        public string PType { get; set; }
        public string WaterBranchCode { get; set; }
        public string WaterStationCode { get; set; }
        public string ElectricBranchCode { get; set; }
        public string ElectricStationCode { get; set; }
        public DateTime? ReadWater { get; set; }
        public DateTime? ReadElectric { get; set; }
        public string ProjectNickName { get; set; }
        public bool? IsUpcountry { get; set; }
        public string SAPProductID_Old { get; set; }
        public string SAPProfitCenter_Old { get; set; }
        public string SAPCostCenter_Old { get; set; }
        public bool? Is3Step { get; set; }
        public DateTime? Change2StepDate { get; set; }
        public bool? IsNotLicenceLand { get; set; }
        public byte[] Logo { get; set; }
        public decimal? PublicFundRate_AP { get; set; }
        public double? PublicFundMonths_AP { get; set; }
        public string ProjectType { get; set; }
        public string ProjectGroup { get; set; }
        public string DocumentName { get; set; }
        public DateTime? EndPreTransferDate { get; set; }
    }

    [Table("ICON_EntForms_Unit")]
    public partial class ICONEntFormsUnit
    {
        [ExplicitKey]
        public string UnitNumber { get; set; }
        public string ProductID { get; set; }
        public string ModelID { get; set; }
        public string PhaseID { get; set; }
        public string SubPhaseID { get; set; }
        public string BlockID { get; set; }
        public decimal? AreaFromRE { get; set; }
        public string TowerID { get; set; }
        public string FloorID { get; set; }
        public int? AssetType { get; set; }
        public int? PlanUnitNumber { get; set; }
        public decimal? Liability { get; set; }
        public decimal? Principal { get; set; }
        public string AddressNumber { get; set; }
        public int? LandStatus { get; set; }
        public DateTime? LandStatusDate { get; set; }
        public string LandStatusNote { get; set; }
        public decimal? EstimatePrice { get; set; }
        public decimal? IncreasingArea { get; set; }
        public DateTime? ApproveDate { get; set; }
        public DateTime? QC5ApprovedDate { get; set; }
        public DateTime? QC6ApprovedDate { get; set; }
        public DateTime? FESTQC6ApprovedDate { get; set; }
        public DateTime? ConstructionStartDate { get; set; }
        public DateTime? ConstructionEndDate { get; set; }
        public DateTime? ConstructionExpectEndDate { get; set; }
        public DateTime? ConstructionRealStartDate { get; set; }
        public string WaterNumber { get; set; }
        public string ElectricNumber { get; set; }
        public decimal? SuggestionPrice { get; set; }
        public DateTime? SuggestionDate { get; set; }
        public string ProductUnit { get; set; }
        public string Package { get; set; }
        public string Progress { get; set; }
        public string FMID { get; set; }
        public string SEID { get; set; }
        public DateTime? DoubleCheckDate { get; set; }
        public DateTime? CheckDate { get; set; }
        public DateTime? RePairDate { get; set; }
        public DateTime? WaterReceiveRequireDate { get; set; }
        public DateTime? WaterRequireWithDrawDate { get; set; }
        public decimal? WaterAdvanceAmount { get; set; }
        public decimal? WaterRealWithDrawAmount { get; set; }
        public DateTime? WaterRequireDate { get; set; }
        public DateTime? WaterInvoildDate { get; set; }
        public DateTime? WaterTransferDate { get; set; }
        public DateTime? WaterTransferDateCustomer { get; set; }
        public string WaterRemark { get; set; }
        public DateTime? ElectricReceiveRequireDate { get; set; }
        public DateTime? ElectricRequireWithdrawDate { get; set; }
        public decimal? ElectricAdvanceAmount { get; set; }
        public decimal? ElectricRealWithdrawAmount { get; set; }
        public DateTime? ElectricRequireDate { get; set; }
        public DateTime? ElectricInvoildDate { get; set; }
        public DateTime? ElectricTransferDate { get; set; }
        public DateTime? ElectricTransferDateCustomer { get; set; }
        public string ElectricRemark { get; set; }
        public decimal? AreaFromPFB { get; set; }
        public string Location { get; set; }
        public int? UnitStatus { get; set; }
        public bool? isDelete { get; set; }
        public string Remark { get; set; }
        public string HistoriesMemo { get; set; }
        public decimal? hedgearea { get; set; }
        public string TitledeedNumber { get; set; }
        public bool? ApproveWaterAdvance { get; set; }
        public bool? ApproveWaterRealWith { get; set; }
        public bool? ApproveElectricAdvance { get; set; }
        public bool? ApproveElectricRealWith { get; set; }
        public DateTime? ClearWaterAdvanceDate { get; set; }
        public DateTime? ClearElectricAdvanceDate { get; set; }
        public DateTime? MeterWaterDate { get; set; }
        public DateTime? MeterElectricDate { get; set; }
        public bool? IsBOI { get; set; }
        public decimal? PrerogativePrice { get; set; }
        public string PrerogativeBank { get; set; }
        public string LandOfficeID { get; set; }
        public int? CaditManagerID { get; set; }
        public double? FenceArea { get; set; }
        public int? HomeNoReceivedDate { get; set; }
        public decimal? EstBuiltinLandPerMetre { get; set; }
        public double? BuiltinLand { get; set; }
        public bool? ISEditUnit { get; set; }
        public bool? LGElectricStatus { get; set; }
        public string LGElectricNumber { get; set; }
        public bool? LGWaterStatus { get; set; }
        public string LGWaterNumber { get; set; }
        public int? Parking { get; set; }
        public int? ParkingIncrease { get; set; }
        public decimal? LoanBankAmount { get; set; }
        public decimal? UnitLoanAmount { get; set; }
        public decimal? BuiltInArea { get; set; }
        public decimal? CurvedsteelArea { get; set; }
        public decimal? FactorArea { get; set; }
        public decimal? AirArea { get; set; }
        public decimal? ParkingArea { get; set; }
        public decimal? VerandaArea { get; set; }
        public string WBSObject { get; set; }
        public string WBSNumber { get; set; }
        public string ModuleBOQ { get; set; }
        public string UnitType { get; set; }
        public bool? isUpdate { get; set; }
        public bool? FirstFlag { get; set; }
        public string WBSStatus { get; set; }
        public string GLRaiseBatchID { get; set; }
        public string OldGLRaiseBatchID { get; set; }
        public string ConstructionModelID { get; set; }
        public int? UnitID { get; set; }
        public string UnitNumber_Old { get; set; }
        public string UnitLayoutType { get; set; }
        public string FloorPlanImage { get; set; }
        public string RoomPlanImage { get; set; }
    }

    [Table("Job")]
    public partial class Job
    {
        [Key]
        public long Id { get; set; }
        public long? StateId { get; set; }
        public string StateName { get; set; }
        public string InvocationData { get; set; }
        public string Arguments { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime? ExpireAt { get; set; }
    }

    [Table("JobParameter")]
    public partial class JobParameter
    {
        [ExplicitKey]
        public long JobId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }

    [Table("JobQueue")]
    public partial class JobQueue
    {
        [Key]
        public int Id { get; set; }
        public long JobId { get; set; }
        public string Queue { get; set; }
        public DateTime? FetchedAt { get; set; }
    }

    [Table("List")]
    public partial class List
    {
        [Key]
        public long Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public DateTime? ExpireAt { get; set; }
    }

    [Table("majordefect")]
    public partial class majordefect
    {
        [Key]
        public int majordefect_id { get; set; }
        public string major_name { get; set; }
    }

    [Table("point")]
    public partial class point
    {
        [Key]
        public int comppoint_id { get; set; }
        public string project { get; set; }
        public string point_name { get; set; }
        public string sub_point { get; set; }
        public string end_point { get; set; }
        public int? cate { get; set; }
        public int? chkmainpoint { get; set; }
        public string floorplantset { get; set; }
        public string producttypecate { get; set; }
    }

    [Table("priorities")]
    public partial class priority
    {
        public int priority_id { get; set; }
        public string _priority { get; set; }
        public string priority_time { get; set; }
        public string time_type { get; set; }
    }

    [Table("ProjectOwner")]
    public partial class ProjectOwner
    {
        [ExplicitKey]
        public string Productid { get; set; }
        public string Productname { get; set; }
        public int? PType { get; set; }
        public string Producttype { get; set; }
        public string SEAFS { get; set; }
        public string PM { get; set; }
        public string PM_SQE { get; set; }
        public string VP { get; set; }
        public string ManagerSE { get; set; }
        public string SSM { get; set; }
        public string LCM { get; set; }
        public string ManagerSSM { get; set; }
        public string Chief { get; set; }
        public int? chkassign { get; set; }
        public string SEAFS_W { get; set; }
        public string PM_W { get; set; }
        public string VP_W { get; set; }
        public string ManagerSE_W { get; set; }
        public string Chief_W { get; set; }
        public int? Chk_W { get; set; }
        public int? ISwecare { get; set; }
        public string PM_Wname { get; set; }
    }

    [Table("ProjectOwnerperiod")]
    public partial class ProjectOwnerperiod
    {
        [ExplicitKey]
        public int pid { get; set; }
        public string Projectid { get; set; }
        public DateTime? Startdate { get; set; }
        public DateTime? Finishdate { get; set; }
        public string PM { get; set; }
    }

    [Table("ProjectOwnerperiodd")]
    public partial class ProjectOwnerperiodd
    {
        [Key]
        public int pid { get; set; }
        public string Productid { get; set; }
        public string Productname { get; set; }
        public DateTime? Startdate { get; set; }
        public DateTime? Finishdate { get; set; }
        public string PM { get; set; }
    }

    [Table("ProjectSeafs")]
    public partial class ProjectSeaf
    {
        [ExplicitKey]
        public string ProductID { get; set; }
        public string Seafs { get; set; }
        public string ProductType { get; set; }
    }

    [Table("ProjectSeafsW")]
    public partial class ProjectSeafsW
    {
        [ExplicitKey]
        public string ProductID { get; set; }
        public string Seafs { get; set; }
        public string ProductType { get; set; }
    }

    [Table("reasons")]
    public partial class reason
    {
        [Key]
        public int reason_id { get; set; }
        public string _reason { get; set; }
    }

    [Table("Schema")]
    public partial class Schema
    {
        [ExplicitKey]
        public int Version { get; set; }
    }

    [Table("SeafsUnit")]
    public partial class SeafsUnit
    {
        public string ProductId { get; set; }
        public string Seafs { get; set; }
        public string UnitNumber { get; set; }
    }

    [Table("SeafsWUnit")]
    public partial class SeafsWUnit
    {
        public string ProductId { get; set; }
        public string Seafs { get; set; }
        public string UnitNumber { get; set; }
    }

    [Table("Server")]
    public partial class Server
    {
        [ExplicitKey]
        public string Id { get; set; }
        public string Data { get; set; }
        public DateTime LastHeartbeat { get; set; }
    }

    [Table("SessionPassThrough")]
    public partial class SessionPassThrough
    {
        [ExplicitKey]
        public Guid SessionId { get; set; }
        public DateTime? SessionDate { get; set; }
        public DateTime? SessionExpiredDate { get; set; }
        public string SessionKey { get; set; }
        public string SessionJsonStringData { get; set; }
    }

    [Table("Set")]
    public partial class Set
    {
        [ExplicitKey]
        public string Key { get; set; }
        public double Score { get; set; }
        public string Value { get; set; }
        public DateTime? ExpireAt { get; set; }
    }

    [Table("State")]
    public partial class State
    {
        [Key]
        public long Id { get; set; }
        public long JobId { get; set; }
        public string Name { get; set; }
        public string Reason { get; set; }
        public DateTime CreatedAt { get; set; }
        public string Data { get; set; }
    }

    [Table("sysdiagrams")]
    public partial class sysdiagram
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        [Key]
        public int diagram_id { get; set; }
        public int? version { get; set; }
        public byte[] definition { get; set; }
    }

    [Table("sysTblDataChangedMonitoring")]
    public partial class sysTblDataChangedMonitoring
    {
        [ExplicitKey]
        public Guid DataChangedId { get; set; }
        public string DataChangedGroupId { get; set; }
        public Guid DataChangedTokenData { get; set; }
        public DateTime DataChangedDatetime { get; set; }
        public string DataChangedFromTable { get; set; }
    }

    [Table("temp_05112015")]
    public partial class temp05112015
    {
        public int TDefectId { get; set; }
        public DateTime? DocOpenDate { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
    }

    [Table("Temp_DailyJob_vwCallDefectReceiveUnitMailApprove")]
    public partial class TempDailyJobvwCallDefectReceiveUnitMailApprove
    {
        public DateTime DataDate { get; set; }
        public string MailRefCode { get; set; }
        public int? TDefectId { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public string SerialNo { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public DateTime? DocTransferDate { get; set; }
        public string DocReceiveUrls { get; set; }
        public string DocReceiveIDs { get; set; }
        public string DocAttachUrls { get; set; }
        public string DocAttachIDs { get; set; }
    }

    [Table("View_TempBlkCustomer")]
    public partial class ViewTempBlkCustomer
    {
        [ExplicitKey]
        public string ProductID { get; set; }
        public string UnitNumber { get; set; }
        public string ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? TransferDate { get; set; }
        public string Mobile { get; set; }
        public int? SellerID { get; set; }
        public string SellerFullName { get; set; }
    }

    [Table("View_TempBlkUnit")]
    public partial class ViewTempBlkUnit
    {
        public string ContractNumber { get; set; }
        public DateTime? ContractDate { get; set; }
        public string BookingNumber { get; set; }
        [ExplicitKey]
        public string ProductID { get; set; }
        public string UnitNumber { get; set; }
        public double? IncreasingArea { get; set; }
        public decimal? NetSalePrice { get; set; }
        public decimal? PaidOtherContract { get; set; }
        public decimal? TransferPayment { get; set; }
        public decimal? TotalPayment { get; set; }
        public string ContractType { get; set; }
        public decimal? Contract2 { get; set; }
        public DateTime? PaymentPeriodStart { get; set; }
        public DateTime? PaymentPeriodEnd { get; set; }
        public int? DownPaymentPeriod { get; set; }
        public decimal? DownPaymentPerMonth { get; set; }
        public decimal? ExtraDownAmount { get; set; }
        public string PromotionID { get; set; }
        public string KasornContractNo { get; set; }
        public DateTime? ApproveDate { get; set; }
        public byte? Cancel { get; set; }
        public DateTime? CancelDate { get; set; }
        public string ModelID { get; set; }
        public string PhaseID { get; set; }
        public string SubPhaseID { get; set; }
        public string BlockID { get; set; }
        public decimal? AreaFromRE { get; set; }
        public string TowerID { get; set; }
        public string FloorID { get; set; }
        public DateTime? BookingDate { get; set; }
        public string IntroducerID { get; set; }
        public decimal? IntroducerAmount { get; set; }
        public string ProductName { get; set; }
        public DateTime? KasornDate { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OldOwnerName { get; set; }
        public string CurrentAddress { get; set; }
        public string Moo { get; set; }
        public string Village { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string PostCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public bool? Header { get; set; }
        public decimal? ContractAmount { get; set; }
        public decimal? DownAmount { get; set; }
        public decimal? AreaFromPFB { get; set; }
        public DateTime? TransferDate { get; set; }
        public byte? CreditType { get; set; }
        public double? PercentBooking { get; set; }
        public double? PercentContract { get; set; }
        public string ExtraDownPayment { get; set; }
        public bool? isPaidCompleted { get; set; }
        public decimal? RemainAmount { get; set; }
        public int? UnitStatus { get; set; }
        public bool? PreApprove { get; set; }
        public string ContractReferent { get; set; }
        public bool? ChangeUnit { get; set; }
        public string PromotionDetail { get; set; }
        public int? CaditManagerID { get; set; }
        public decimal? q { get; set; }
        public decimal? w { get; set; }
        public decimal? SpacialDiscount { get; set; }
        public decimal? BoiDiscount { get; set; }
        public decimal? EmployeeDiscount { get; set; }
        public decimal? PheuksaPrice { get; set; }
        public bool? IsBOI { get; set; }
        public string Producttype { get; set; }
        public string BrandID { get; set; }
        public decimal? PromotionDiscount { get; set; }
        public double? PercentDownPayment { get; set; }
        public int? HomeNoReceivedDate { get; set; }
        public string Remark { get; set; }
        public decimal? TotalSellingPrice { get; set; }
        public decimal? KasornPrice { get; set; }
        public decimal? BookingAmount { get; set; }
        public decimal? UnitIncreasingAreaPrice { get; set; }
        public string BookingReceivedID { get; set; }
        public decimal? SellingPrice { get; set; }
        public bool? isNeedSpecialDis { get; set; }
        public decimal? AdditionalDiscount { get; set; }
        public string Subordinator { get; set; }
        public decimal? PromotionPrice { get; set; }
        public decimal? CashDiscount { get; set; }
        public decimal? TransferDiscount { get; set; }
        public string CompanyID { get; set; }
        public string AddressNumber { get; set; }
        public string ModelHomeThai { get; set; }
        public string SBUID { get; set; }
        public string BUID { get; set; }
        public string PType { get; set; }
        public int? AssetType { get; set; }
        public DateTime? ExpireInsuranceDate { get; set; }
        public int? chkInsurance { get; set; }
        public string WBSNumber { get; set; }
    }

    [Table("View_UnitCustomer")]
    public partial class ViewUnitCustomer
    {
        [ExplicitKey]
        public string ProductID { get; set; }
        public string UnitNumber { get; set; }
        public string ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? TransferDate { get; set; }
        public string Mobile { get; set; }
        public int? SellerID { get; set; }
        public string SellerFullName { get; set; }
        public string ContractNumber { get; set; }
        public string BookingNumber { get; set; }
    }

    [Table("vw_Constructor")]
    public partial class vwConstructor
    {
        public string ProductID { get; set; }
        public string Project { get; set; }
        public string UnitNumber { get; set; }
        public string WBSNumber { get; set; }
        public string M_CONSTRUCTOR_NAME { get; set; }
        public int? M_SAP_CODE { get; set; }
    }

    [Table("vw_job_View_TempBlkCustomer")]
    public partial class vwjobViewTempBlkCustomer
    {
        public string ProductID { get; set; }
        public string UnitNumber { get; set; }
        public string ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? TransferDate { get; set; }
        public string Mobile { get; set; }
        public int? SellerID { get; set; }
        public string SellerFullName { get; set; }
    }

    [Table("vw_job_View_TempBlkUnit")]
    public partial class vwjobViewTempBlkUnit
    {
        public string ContractNumber { get; set; }
        public DateTime? ContractDate { get; set; }
        public string BookingNumber { get; set; }
        public string ProductID { get; set; }
        public string UnitNumber { get; set; }
        public double? IncreasingArea { get; set; }
        public decimal? NetSalePrice { get; set; }
        public decimal? PaidOtherContract { get; set; }
        public decimal? TransferPayment { get; set; }
        public decimal? TotalPayment { get; set; }
        public string ContractType { get; set; }
        public decimal? Contract2 { get; set; }
        public DateTime? PaymentPeriodStart { get; set; }
        public DateTime? PaymentPeriodEnd { get; set; }
        public int? DownPaymentPeriod { get; set; }
        public decimal? DownPaymentPerMonth { get; set; }
        public decimal? ExtraDownAmount { get; set; }
        public string PromotionID { get; set; }
        public string KasornContractNo { get; set; }
        public DateTime? ApproveDate { get; set; }
        public byte? Cancel { get; set; }
        public DateTime? CancelDate { get; set; }
        public string ModelID { get; set; }
        public string PhaseID { get; set; }
        public string SubPhaseID { get; set; }
        public string BlockID { get; set; }
        public decimal? AreaFromRE { get; set; }
        public string TowerID { get; set; }
        public string FloorID { get; set; }
        public DateTime? BookingDate { get; set; }
        public string IntroducerID { get; set; }
        public decimal? IntroducerAmount { get; set; }
        public string ProductName { get; set; }
        public DateTime? KasornDate { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OldOwnerName { get; set; }
        public string CurrentAddress { get; set; }
        public string Moo { get; set; }
        public string Village { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public string SubDistrict { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string PostCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public bool? Header { get; set; }
        public decimal? ContractAmount { get; set; }
        public decimal? DownAmount { get; set; }
        public decimal? AreaFromPFB { get; set; }
        public DateTime? TransferDate { get; set; }
        public byte? CreditType { get; set; }
        public double? PercentBooking { get; set; }
        public double? PercentContract { get; set; }
        public string ExtraDownPayment { get; set; }
        public bool? isPaidCompleted { get; set; }
        public decimal? RemainAmount { get; set; }
        public int? UnitStatus { get; set; }
        public bool? PreApprove { get; set; }
        public string ContractReferent { get; set; }
        public bool? ChangeUnit { get; set; }
        public string PromotionDetail { get; set; }
        public int? CaditManagerID { get; set; }
        public decimal? q { get; set; }
        public decimal? w { get; set; }
        public decimal? SpacialDiscount { get; set; }
        public decimal? BoiDiscount { get; set; }
        public decimal? EmployeeDiscount { get; set; }
        public decimal? PheuksaPrice { get; set; }
        public bool? IsBOI { get; set; }
        public string Producttype { get; set; }
        public string BrandID { get; set; }
        public decimal? PromotionDiscount { get; set; }
        public double? PercentDownPayment { get; set; }
        public int? HomeNoReceivedDate { get; set; }
        public string Remark { get; set; }
        public decimal? TotalSellingPrice { get; set; }
        public decimal? KasornPrice { get; set; }
        public decimal? BookingAmount { get; set; }
        public decimal? UnitIncreasingAreaPrice { get; set; }
        public string BookingReceivedID { get; set; }
        public decimal? SellingPrice { get; set; }
        public bool? isNeedSpecialDis { get; set; }
        public decimal? AdditionalDiscount { get; set; }
        public string Subordinator { get; set; }
        public decimal? PromotionPrice { get; set; }
        public decimal? CashDiscount { get; set; }
        public decimal? TransferDiscount { get; set; }
        public string CompanyID { get; set; }
        public string AddressNumber { get; set; }
        public string ModelHomeThai { get; set; }
        public string SBUID { get; set; }
        public string BUID { get; set; }
        public string PType { get; set; }
        public int? AssetType { get; set; }
        public DateTime? ExpireInsuranceDate { get; set; }
        public int? chkInsurance { get; set; }
        public string WBSNumber { get; set; }
    }

    [Table("vwCallDefectAPIDownloadUnit")]
    public partial class vwCallDefectAPIDownloadUnit
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductNameEN { get; set; }
        public string ProductNickName { get; set; }
        public string ProductType { get; set; }
        public string ProductTypeCate { get; set; }
        public string UnitNumber { get; set; }
        public string AddressNumber { get; set; }
        public string WbsNumber { get; set; }
        public string ModelID { get; set; }
        public string ModelHomeThai { get; set; }
        public string ModelHomeEng { get; set; }
        public string ModelLayoutType { get; set; }
        public decimal? AreaFromRE { get; set; }
        public string PhaseBuildingName { get; set; }
        public string Phase { get; set; }
        public string Tower { get; set; }
        public string Floor { get; set; }
        public string ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CustomerFullName { get; set; }
        public string ContactTel { get; set; }
        public DateTime? TransferDueDate { get; set; }
        public DateTime? TransferDate { get; set; }
        public string BookingNumber { get; set; }
        public string ContractNumber { get; set; }
        public int? SellerID { get; set; }
        public string SellerFullName { get; set; }
        public int? AppointmentJobNo { get; set; }
        public string DFSysPrev_TDefectDocNo { get; set; }
        public DateTime? DFSysPrev_DocOpenDate { get; set; }
        public int? DFSysPrev_CustRoundAuditNo { get; set; }
        public string DFSysPrev_ContactID { get; set; }
        public string DFSysPrev_ContactName { get; set; }
        public DateTime DFSysPrev_DownloadDataDate { get; set; }
    }

    [Table("vwCallDefectAppointment")]
    public partial class vwCallDefectAppointment
    {
        public int DFAPID { get; set; }
        public string ProductId { get; set; }
        public string unitnumber { get; set; }
        public int? idjobno { get; set; }
        public DateTime? appdate { get; set; }
        public DateTime? appdate_putoff { get; set; }
        public int? confirmapp { get; set; }
        public DateTime? appdate2 { get; set; }
        public DateTime? appdate2_putoff { get; set; }
        public int? confirmapp2 { get; set; }
        public DateTime? appdate3 { get; set; }
        public DateTime? appdate3_putoff { get; set; }
        public int? confirmapp3 { get; set; }
        public DateTime? appdate4 { get; set; }
        public DateTime? appdate4_putoff { get; set; }
        public int? confirmapp4 { get; set; }
        public DateTime? appdate5 { get; set; }
        public DateTime? appdate5_putoff { get; set; }
        public int? confirmapp5 { get; set; }
        public string appnote { get; set; }
        public string appby { get; set; }
        public string confirmappby { get; set; }
        public string cusomer_id { get; set; }
        public string cusomer_name { get; set; }
        public string customer_contacttel { get; set; }
        public string AppByName { get; set; }
        public string ConfirMappByName { get; set; }
        public string ConfirMappStatus { get; set; }
    }

    [Table("vwCallDefectAppointmentTimeList")]
    public partial class vwCallDefectAppointmentTimeList
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    [Table("vwCallDefectReceiveUnitDoc")]
    public partial class vwCallDefectReceiveUnitDoc
    {
        public int ResourceId { get; set; }
        public string ProjectNo { get; set; }
        public string SerialNo { get; set; }
        public string RAuditNo { get; set; }
        public int? TDefectId { get; set; }
        public DateTime? DocOpenDate { get; set; }
        public string TDefectDocNo { get; set; }
        public int? ResourceType { get; set; }
        public string ResourceTypeDesc { get; set; }
        public string ResourceMineType { get; set; }
        public string ResourceTagCode { get; set; }
        public string ResourceTagSubCode { get; set; }
        public string FilePhyPath { get; set; }
        public string FileUrl { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public string ContactID { get; set; }
        public string ContactName { get; set; }
        public bool? DocIsActive { get; set; }
    }

    [Table("vwCallDefectReceiveUnitDocRAudit")]
    public partial class vwCallDefectReceiveUnitDocRAudit
    {
        public int ResourceId { get; set; }
        public string ProjectNo { get; set; }
        public string SerialNo { get; set; }
        public string RAuditNo { get; set; }
        public int? TDefectId { get; set; }
        public DateTime? DocOpenDate { get; set; }
        public string TDefectDocNo { get; set; }
        public int? ResourceType { get; set; }
        public string ResourceTypeDesc { get; set; }
        public string ResourceMineType { get; set; }
        public string ResourceTagCode { get; set; }
        public string ResourceTagSubCode { get; set; }
        public string FilePhyPath { get; set; }
        public string FileUrl { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public string ContactID { get; set; }
        public string ContactName { get; set; }
        public bool? DocIsActive { get; set; }
    }

    [Table("vwCallDefectReceiveUnitMailApprove")]
    public partial class vwCallDefectReceiveUnitMailApprove
    {
        public DateTime DataDate { get; set; }
        public string MailRefCode { get; set; }
        public int? TDefectId { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public string SerialNo { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public DateTime? DocTransferDate { get; set; }
        public string DocReceiveUrls { get; set; }
        public string DocReceiveIDs { get; set; }
        public string DocAttachUrls { get; set; }
        public string DocAttachIDs { get; set; }
    }

    [Table("vwCallDefectReportOfRoundSignSequence")]
    public partial class vwCallDefectReportOfRoundSignSequence
    {
        public string ProjectNo { get; set; }
        public string SerialNo { get; set; }
        public string TDefectDocNo { get; set; }
        public string DefectDocUrl { get; set; }
        public string SigndSeqNo { get; set; }
        public DateTime? SigndDate { get; set; }
        public int? SigndOnRoundAuditNo { get; set; }
    }

    [Table("vwCallDefectResource")]
    public partial class vwCallDefectResource
    {
        public int ResourceId { get; set; }
        public string ProjectNo { get; set; }
        public string SerialNo { get; set; }
        public int? TDefectId { get; set; }
        public int? ResourceType { get; set; }
        public string ResourceTypeDesc { get; set; }
        public string ResourceMineType { get; set; }
        public string ResourceTagCode { get; set; }
        public string ResourceTagSubCode { get; set; }
        public string FilePhyPath { get; set; }
        public string FileUrl { get; set; }
        public string Description { get; set; }
    }

    [Table("vwCallDefectRoundAudit")]
    public partial class vwCallDefectRoundAudit
    {
        public string ProjectNo { get; set; }
        public string Unit { get; set; }
        public int DefectDocId { get; set; }
        public string DocNo { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public int RAuditNo { get; set; }
        public int? RAuditNumOfTask { get; set; }
        public string RAuditTaskNo { get; set; }
        public string RAuditDateQuater { get; set; }
        public DateTime? RAuditDate { get; set; }
        public DateTime? RAuditOpenDateTime { get; set; }
        public DateTime? RAuditCloseDueDate { get; set; }
        public DateTime? RAuditProcessDate { get; set; }
        public DateTime? RAuditFinishDate { get; set; }
        public DateTime? RAuditCloseDate { get; set; }
        public string RAuditStatus { get; set; }
        public int IsZeroDefect { get; set; }
        public string ContactID { get; set; }
        public string ContactName { get; set; }
        public bool? DocIsActive { get; set; }
        public bool? DocIsExternalAudit { get; set; }
        public bool? DocIsReqUnitReceiveAttachFile { get; set; }
    }

    [Table("vwCallDefectRoundAudit_bk")]
    public partial class vwCallDefectRoundAuditbk
    {
        public string ProjectNo { get; set; }
        public string Unit { get; set; }
        public int DefectDocId { get; set; }
        public string DocNo { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public int? RAuditNo { get; set; }
        public int? RAuditNumOfTask { get; set; }
        public string RAuditTaskNo { get; set; }
        public string RAuditDateQuater { get; set; }
        public DateTime? RAuditDate { get; set; }
        public DateTime? RAuditOpenDateTime { get; set; }
        public DateTime? RAuditCloseDueDate { get; set; }
        public DateTime? RAuditProcessDate { get; set; }
        public DateTime? RAuditFinishDate { get; set; }
        public DateTime? RAuditCloseDate { get; set; }
        public string RAuditStatus { get; set; }
        public int IsZeroDefect { get; set; }
        public string ContactID { get; set; }
        public string ContactName { get; set; }
        public bool? DocIsActive { get; set; }
        public bool? DocIsExternalAudit { get; set; }
        public bool? DocIsReqUnitReceiveAttachFile { get; set; }
    }

    [Table("vwCallDefectRoundAudit_old")]
    public partial class vwCallDefectRoundAuditold
    {
        public string ProjectNo { get; set; }
        public string Unit { get; set; }
        public int DefectDocId { get; set; }
        public string DocNo { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public int? RAuditNo { get; set; }
        public int? RAuditNumOfTask { get; set; }
        public string RAuditTaskNo { get; set; }
        public string RAuditDateQuater { get; set; }
        public DateTime? RAuditDate { get; set; }
        public DateTime? RAuditOpenDateTime { get; set; }
        public DateTime? RAuditCloseDueDate { get; set; }
        public DateTime? RAuditProcessDate { get; set; }
        public DateTime? RAuditFinishDate { get; set; }
        public DateTime? RAuditCloseDate { get; set; }
        public string RAuditStatus { get; set; }
        public int IsZeroDefect { get; set; }
        public string ContactID { get; set; }
        public string ContactName { get; set; }
        public bool? DocIsActive { get; set; }
        public bool? DocIsExternalAudit { get; set; }
        public bool? DocIsReqUnitReceiveAttachFile { get; set; }
    }

    [Table("vwCallDefectRoundAudit_Protected")]
    public partial class vwCallDefectRoundAuditProtected
    {
        public string ProjectNo { get; set; }
        public string Unit { get; set; }
        public int DefectDocId { get; set; }
        public string DocNo { get; set; }
        public DateTime? DocReceiveUnitDate { get; set; }
        public int RAuditNo { get; set; }
        public int? RAuditNumOfTask { get; set; }
        public string RAuditTaskNo { get; set; }
        public string RAuditDateQuater { get; set; }
        public DateTime? RAuditDate { get; set; }
        public DateTime? RAuditOpenDateTime { get; set; }
        public DateTime? RAuditCloseDueDate { get; set; }
        public DateTime? RAuditProcessDate { get; set; }
        public DateTime? RAuditFinishDate { get; set; }
        public DateTime? RAuditCloseDate { get; set; }
        public string RAuditStatus { get; set; }
        public int IsZeroDefect { get; set; }
        public string ContactID { get; set; }
        public string ContactName { get; set; }
        public bool? DocIsActive { get; set; }
        public bool? DocIsExternalAudit { get; set; }
        public bool? DocIsReqUnitReceiveAttachFile { get; set; }
    }

    [Table("vwCallDefectWebInquiryDataList")]
    public partial class vwCallDefectWebInquiryDataList
    {
        public string BU { get; set; }
        public string ProductTypeCate { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public string BookingNo { get; set; }
        public string ContractNumber { get; set; }
        public DateTime? TransferDate { get; set; }
        public string TransferStatus { get; set; }
        public int DefectDocId { get; set; }
        public string DefectDocNo { get; set; }
        public string DefectDocFileUrl { get; set; }
        public string AddressNo { get; set; }
        public string ContactFullName { get; set; }
        public int AuditRoundNo { get; set; }
        public string IsZeroDefect { get; set; }
        public int? NumOfTaskDefect { get; set; }
        public DateTime? AuditDate { get; set; }
        public DateTime? AuditFinishDate { get; set; }
        public string IsCustSignRecUnit { get; set; }
        public DateTime? CustSignRecUnitDate { get; set; }
        public string DocIsExternalAudit { get; set; }
        public string DocIsReqUnitReceiveAttachFile { get; set; }
        public string AuditStatus { get; set; }
        public string AuditStatusName { get; set; }
        public string AttachUnitReceiveResIDs { get; set; }
        public bool DefectDocStatus { get; set; }
    }

    [Table("vwCallservice_FloorPlanNotAvailable")]
    public partial class vwCallserviceFloorPlanNotAvailable
    {
        public string FloorPlanImageId { get; set; }
        public string ProductID { get; set; }
        public string UnitLayoutType { get; set; }
        public string ProductType { get; set; }
        public string ProductTypeCate { get; set; }
    }

    [Table("vwCallservice_FloorPlanReady")]
    public partial class vwCallserviceFloorPlanReady
    {
        public string FloorPlanImageId { get; set; }
        public string ProductID { get; set; }
        public string UnitLayoutType { get; set; }
    }

    [Table("vwCallservice_LinkQueryCRMDirectProjectActive")]
    public partial class vwCallserviceLinkQueryCRMDirectProjectActive
    {
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductNameEN { get; set; }
        public string ProductType { get; set; }
        public string ProductTypeCate { get; set; }
        public string BrandName { get; set; }
    }

    [Table("vwCallservice_LinkQueryCRMDirectProjectActiveUnitData")]
    public partial class vwCallserviceLinkQueryCRMDirectProjectActiveUnitData
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductNameEN { get; set; }
        public string ProductNickName { get; set; }
        public string ProductType { get; set; }
        public string ProductTypeCate { get; set; }
        public string UnitNumber { get; set; }
        public string AddressNumber { get; set; }
        public string WbsNumber { get; set; }
        public string ModelID { get; set; }
        public string ModelHomeThai { get; set; }
        public string ModelHomeEng { get; set; }
        public string ModelLayoutType { get; set; }
        public decimal? AreaFromRE { get; set; }
        public string PhaseBuildingName { get; set; }
        public string Phase { get; set; }
        public string Tower { get; set; }
        public string Floor { get; set; }
        public string ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CustomerFullName { get; set; }
        public string ContactTel { get; set; }
        public DateTime? TransferDueDate { get; set; }
        public DateTime? TransferDate { get; set; }
        public string BookingNumber { get; set; }
        public string ContractNumber { get; set; }
        public int? SellerID { get; set; }
        public string SellerFullName { get; set; }
        public int? AppointmentJobNo { get; set; }
    }

    [Table("vwCallservice_LinkQueryCRMDirectProjectPhaseBuildingData")]
    public partial class vwCallserviceLinkQueryCRMDirectProjectPhaseBuildingData
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductNameEN { get; set; }
        public string PType { get; set; }
        public string PhaseBuildingName { get; set; }
        public int? NumMaxOfFloor { get; set; }
        public int? NumStartOfFloor { get; set; }
        public string TowerID { get; set; }
        public string WBSPhase { get; set; }
    }

    [Table("vwProductBU")]
    public partial class vwProductBU
    {
        public string Productid { get; set; }
        public string Productname { get; set; }
        public string ProductBU { get; set; }
        public bool? IsFixit { get; set; }
    }
}
