//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSerInstance
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webSerInstance.AuthorizeSoap")]
    public interface AuthorizeSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.UserLoginResponse> UserLoginAsync(webSerInstance.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin_IP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.UserLogin_IPResponse> UserLogin_IPAsync(webSerInstance.UserLogin_IPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUserProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.FindUserProfileResponse> FindUserProfileAsync(webSerInstance.FindUserProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.GetCurrentDomainResponse> GetCurrentDomainAsync(webSerInstance.GetCurrentDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUserProjectByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.FindUserProjectByUserIDResponse> FindUserProjectByUserIDAsync(webSerInstance.FindUserProjectByUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUserProjectByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.FindUserProjectByUserNameResponse> FindUserProjectByUserNameAsync(webSerInstance.FindUserProjectByUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUserAppUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.FindUserAppUserIDResponse> FindUserAppUserIDAsync(webSerInstance.FindUserAppUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindUserAppUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.FindUserAppUserNameResponse> FindUserAppUserNameAsync(webSerInstance.FindUserAppUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadAllEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.LoadAllEmployeeResponse> LoadAllEmployeeAsync(webSerInstance.LoadAllEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadCompany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.LoadCompanyResponse> LoadCompanyAsync(webSerInstance.LoadCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDivision", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.LoadDivisionResponse> LoadDivisionAsync(webSerInstance.LoadDivisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.LoadDepartmentResponse> LoadDepartmentAsync(webSerInstance.LoadDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadSection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.LoadSectionResponse> LoadSectionAsync(webSerInstance.LoadSectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.LoadUnitResponse> LoadUnitAsync(webSerInstance.LoadUnitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.LoadProjectResponse> LoadProjectAsync(webSerInstance.LoadProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadPosition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<webSerInstance.LoadPositionResponse> LoadPositionAsync(webSerInstance.LoadPositionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeSoapHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _UserAppData
    {
        
        private string _UserAppField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string _UserApp
        {
            get
            {
                return this._UserAppField;
            }
            set
            {
                this._UserAppField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class _UserProjectData
    {
        
        private string _UserProjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string _UserProject
        {
            get
            {
                return this._UserProjectField;
            }
            set
            {
                this._UserProjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AutorizeData
    {
        
        private bool loginResultField;
        
        private string loginResultMessageField;
        
        private string userPrincipalNameField;
        
        private string domainUserNameField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string displayNameField;
        
        private string employeeIDField;
        
        private string emailField;
        
        private string divisionField;
        
        private System.Nullable<System.DateTime> accountExpirationDateField;
        
        private System.Nullable<System.DateTime> lastLogonField;
        
        private string authenticationProviderField;
        
        private string sysUserIdField;
        
        private string sysUserDataField;
        
        private string sysUserRolesField;
        
        private string sysAppCodeField;
        
        private string userProjectField;
        
        private string userAppField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool LoginResult
        {
            get
            {
                return this.loginResultField;
            }
            set
            {
                this.loginResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LoginResultMessage
        {
            get
            {
                return this.loginResultMessageField;
            }
            set
            {
                this.loginResultMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserPrincipalName
        {
            get
            {
                return this.userPrincipalNameField;
            }
            set
            {
                this.userPrincipalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DomainUserName
        {
            get
            {
                return this.domainUserNameField;
            }
            set
            {
                this.domainUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EmployeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Division
        {
            get
            {
                return this.divisionField;
            }
            set
            {
                this.divisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> AccountExpirationDate
        {
            get
            {
                return this.accountExpirationDateField;
            }
            set
            {
                this.accountExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> LastLogon
        {
            get
            {
                return this.lastLogonField;
            }
            set
            {
                this.lastLogonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AuthenticationProvider
        {
            get
            {
                return this.authenticationProviderField;
            }
            set
            {
                this.authenticationProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SysUserId
        {
            get
            {
                return this.sysUserIdField;
            }
            set
            {
                this.sysUserIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string SysUserData
        {
            get
            {
                return this.sysUserDataField;
            }
            set
            {
                this.sysUserDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SysUserRoles
        {
            get
            {
                return this.sysUserRolesField;
            }
            set
            {
                this.sysUserRolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string SysAppCode
        {
            get
            {
                return this.sysAppCodeField;
            }
            set
            {
                this.sysAppCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string UserProject
        {
            get
            {
                return this.userProjectField;
            }
            set
            {
                this.userProjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string UserApp
        {
            get
            {
                return this.userAppField;
            }
            set
            {
                this.userAppField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLoginRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string AppCode;
        
        public UserLoginRequest()
        {
        }
        
        public UserLoginRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string User, string Password, string AppCode)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.User = User;
            this.Password = Password;
            this.AppCode = AppCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLoginResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public webSerInstance.AutorizeData UserLoginResult;
        
        public UserLoginResponse()
        {
        }
        
        public UserLoginResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, webSerInstance.AutorizeData UserLoginResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.UserLoginResult = UserLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin_IP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLogin_IPRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string AppCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ClientIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ClientName;
        
        public UserLogin_IPRequest()
        {
        }
        
        public UserLogin_IPRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string User, string Password, string AppCode, string ClientIP, string ClientName)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.User = User;
            this.Password = Password;
            this.AppCode = AppCode;
            this.ClientIP = ClientIP;
            this.ClientName = ClientName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserLogin_IPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UserLogin_IPResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public webSerInstance.AutorizeData UserLogin_IPResult;
        
        public UserLogin_IPResponse()
        {
        }
        
        public UserLogin_IPResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, webSerInstance.AutorizeData UserLogin_IPResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.UserLogin_IPResult = UserLogin_IPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserProfile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserProfileRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string AppCode;
        
        public FindUserProfileRequest()
        {
        }
        
        public FindUserProfileRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string User, string AppCode)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.User = User;
            this.AppCode = AppCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserProfileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserProfileResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public webSerInstance.AutorizeData FindUserProfileResult;
        
        public FindUserProfileResponse()
        {
        }
        
        public FindUserProfileResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, webSerInstance.AutorizeData FindUserProfileResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.FindUserProfileResult = FindUserProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentDomain", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCurrentDomainRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public GetCurrentDomainRequest()
        {
        }
        
        public GetCurrentDomainRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrentDomainResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCurrentDomainResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetCurrentDomainResult;
        
        public GetCurrentDomainResponse()
        {
        }
        
        public GetCurrentDomainResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string GetCurrentDomainResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.GetCurrentDomainResult = GetCurrentDomainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserProjectByUserID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserProjectByUserIDRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string User;
        
        public FindUserProjectByUserIDRequest()
        {
        }
        
        public FindUserProjectByUserIDRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string User)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserProjectByUserIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserProjectByUserIDResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public webSerInstance._UserProjectData FindUserProjectByUserIDResult;
        
        public FindUserProjectByUserIDResponse()
        {
        }
        
        public FindUserProjectByUserIDResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, webSerInstance._UserProjectData FindUserProjectByUserIDResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.FindUserProjectByUserIDResult = FindUserProjectByUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserProjectByUserName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserProjectByUserNameRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string User;
        
        public FindUserProjectByUserNameRequest()
        {
        }
        
        public FindUserProjectByUserNameRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string User)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserProjectByUserNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserProjectByUserNameResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public webSerInstance._UserProjectData FindUserProjectByUserNameResult;
        
        public FindUserProjectByUserNameResponse()
        {
        }
        
        public FindUserProjectByUserNameResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, webSerInstance._UserProjectData FindUserProjectByUserNameResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.FindUserProjectByUserNameResult = FindUserProjectByUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserAppUserID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserAppUserIDRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string User;
        
        public FindUserAppUserIDRequest()
        {
        }
        
        public FindUserAppUserIDRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string User)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserAppUserIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserAppUserIDResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public webSerInstance._UserAppData FindUserAppUserIDResult;
        
        public FindUserAppUserIDResponse()
        {
        }
        
        public FindUserAppUserIDResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, webSerInstance._UserAppData FindUserAppUserIDResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.FindUserAppUserIDResult = FindUserAppUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserAppUserName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserAppUserNameRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string User;
        
        public FindUserAppUserNameRequest()
        {
        }
        
        public FindUserAppUserNameRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string User)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindUserAppUserNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindUserAppUserNameResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public webSerInstance._UserAppData FindUserAppUserNameResult;
        
        public FindUserAppUserNameResponse()
        {
        }
        
        public FindUserAppUserNameResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, webSerInstance._UserAppData FindUserAppUserNameResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.FindUserAppUserNameResult = FindUserAppUserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadAllEmployee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadAllEmployeeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public LoadAllEmployeeRequest()
        {
        }
        
        public LoadAllEmployeeRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadAllEmployeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadAllEmployeeResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoadAllEmployeeResult;
        
        public LoadAllEmployeeResponse()
        {
        }
        
        public LoadAllEmployeeResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string LoadAllEmployeeResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.LoadAllEmployeeResult = LoadAllEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadCompany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadCompanyRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public LoadCompanyRequest()
        {
        }
        
        public LoadCompanyRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadCompanyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadCompanyResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoadCompanyResult;
        
        public LoadCompanyResponse()
        {
        }
        
        public LoadCompanyResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string LoadCompanyResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.LoadCompanyResult = LoadCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadDivision", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadDivisionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public LoadDivisionRequest()
        {
        }
        
        public LoadDivisionRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadDivisionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadDivisionResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoadDivisionResult;
        
        public LoadDivisionResponse()
        {
        }
        
        public LoadDivisionResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string LoadDivisionResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.LoadDivisionResult = LoadDivisionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadDepartment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadDepartmentRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public LoadDepartmentRequest()
        {
        }
        
        public LoadDepartmentRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadDepartmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadDepartmentResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoadDepartmentResult;
        
        public LoadDepartmentResponse()
        {
        }
        
        public LoadDepartmentResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string LoadDepartmentResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.LoadDepartmentResult = LoadDepartmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadSection", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadSectionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public LoadSectionRequest()
        {
        }
        
        public LoadSectionRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadSectionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadSectionResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoadSectionResult;
        
        public LoadSectionResponse()
        {
        }
        
        public LoadSectionResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string LoadSectionResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.LoadSectionResult = LoadSectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadUnit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadUnitRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public LoadUnitRequest()
        {
        }
        
        public LoadUnitRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadUnitResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadUnitResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoadUnitResult;
        
        public LoadUnitResponse()
        {
        }
        
        public LoadUnitResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string LoadUnitResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.LoadUnitResult = LoadUnitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadProject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadProjectRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public LoadProjectRequest()
        {
        }
        
        public LoadProjectRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadProjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadProjectResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoadProjectResult;
        
        public LoadProjectResponse()
        {
        }
        
        public LoadProjectResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string LoadProjectResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.LoadProjectResult = LoadProjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadPosition", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadPositionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        public LoadPositionRequest()
        {
        }
        
        public LoadPositionRequest(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadPositionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadPositionResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LoadPositionResult;
        
        public LoadPositionResponse()
        {
        }
        
        public LoadPositionResponse(webSerInstance.AuthorizeSoapHeader AuthorizeSoapHeader, string LoadPositionResult)
        {
            this.AuthorizeSoapHeader = AuthorizeSoapHeader;
            this.LoadPositionResult = LoadPositionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface AuthorizeSoapChannel : webSerInstance.AuthorizeSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class AuthorizeSoapClient : System.ServiceModel.ClientBase<webSerInstance.AuthorizeSoap>, webSerInstance.AuthorizeSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthorizeSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthorizeSoapClient.GetBindingForEndpoint(endpointConfiguration), AuthorizeSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthorizeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthorizeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<webSerInstance.UserLoginResponse> UserLoginAsync(webSerInstance.UserLoginRequest request)
        {
            return base.Channel.UserLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.UserLogin_IPResponse> UserLogin_IPAsync(webSerInstance.UserLogin_IPRequest request)
        {
            return base.Channel.UserLogin_IPAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.FindUserProfileResponse> FindUserProfileAsync(webSerInstance.FindUserProfileRequest request)
        {
            return base.Channel.FindUserProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.GetCurrentDomainResponse> GetCurrentDomainAsync(webSerInstance.GetCurrentDomainRequest request)
        {
            return base.Channel.GetCurrentDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.FindUserProjectByUserIDResponse> FindUserProjectByUserIDAsync(webSerInstance.FindUserProjectByUserIDRequest request)
        {
            return base.Channel.FindUserProjectByUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.FindUserProjectByUserNameResponse> FindUserProjectByUserNameAsync(webSerInstance.FindUserProjectByUserNameRequest request)
        {
            return base.Channel.FindUserProjectByUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.FindUserAppUserIDResponse> FindUserAppUserIDAsync(webSerInstance.FindUserAppUserIDRequest request)
        {
            return base.Channel.FindUserAppUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.FindUserAppUserNameResponse> FindUserAppUserNameAsync(webSerInstance.FindUserAppUserNameRequest request)
        {
            return base.Channel.FindUserAppUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.LoadAllEmployeeResponse> LoadAllEmployeeAsync(webSerInstance.LoadAllEmployeeRequest request)
        {
            return base.Channel.LoadAllEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.LoadCompanyResponse> LoadCompanyAsync(webSerInstance.LoadCompanyRequest request)
        {
            return base.Channel.LoadCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.LoadDivisionResponse> LoadDivisionAsync(webSerInstance.LoadDivisionRequest request)
        {
            return base.Channel.LoadDivisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.LoadDepartmentResponse> LoadDepartmentAsync(webSerInstance.LoadDepartmentRequest request)
        {
            return base.Channel.LoadDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.LoadSectionResponse> LoadSectionAsync(webSerInstance.LoadSectionRequest request)
        {
            return base.Channel.LoadSectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.LoadUnitResponse> LoadUnitAsync(webSerInstance.LoadUnitRequest request)
        {
            return base.Channel.LoadUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.LoadProjectResponse> LoadProjectAsync(webSerInstance.LoadProjectRequest request)
        {
            return base.Channel.LoadProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<webSerInstance.LoadPositionResponse> LoadPositionAsync(webSerInstance.LoadPositionRequest request)
        {
            return base.Channel.LoadPositionAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthorizeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AuthorizeSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthorizeSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.40/authorizewebservice/Authorize.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AuthorizeSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.40/authorizewebservice/Authorize.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AuthorizeSoap,
            
            AuthorizeSoap12,
        }
    }
}
